name: Daily Wallet Snapshot

on:
  schedule:
    # Run shortly after 00:00 UTC and 23:59 UTC windows
    - cron: '5 0 * * *'
    - cron: '55 23 * * *'
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run daily snapshot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
        run: npm run snapshot:daily


