name: Wallet Monitor Scheduler

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:

jobs:
  check-wallet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run wallet check script
        env:
          KOIOS_API_KEY: ${{ secrets.KOIOS_API_KEY }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: npm run wallet:check
